apiVersion: batch/v1
kind: CronJob
metadata:
  name: batch-job
spec:
  schedule: '0 2 * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: batch
              image: batch-job:latest
          restartPolicy: OnFailure
